### ISSUE TITLE
Xcode 16

### ISSUE THREAD

**Issue by pnewell** [johnno1962/InjectionNext#1]
Is this working with Xcode 16 beta? I have tried and confirmed linker flags are right but when I save a file I still get the error:

🔥 ℹ️ No symbols replaced, have you added -Xlinker -interposable to your project's Debug configuration "Other Linker Flags"?

**Comment by johnno1962** [comment]
Hi, this is looking like a new issue https://github.com/johnno1962/HotReloading/issues/95#issuecomment-2161116406 where the -interposbale flag is ignored in the new beta. We'll have to see how this develops.

**Comment by johnno1962** [comment]
This should be resolved now if you sync to HotReloading 5.0.5.
