### ISSUE TITLE
Build Error: Undefined symbols for architecture arm64 when integrating as Swift Package

### ISSUE THREAD

**Issue by wolfcolony** [johnno1962/InjectionNext#15]
Hello,

I'm encountering a build error when trying to integrate InjectionNext as a Swift Package in a new Xcode project. Here's the error I'm seeing:

```
Undefined symbols for architecture arm64:  
  "_DLKit_appImagesContain", referenced from:  
      +[NSObject(InjectionBoot) load] in InjectionBoot.o  
  "_OBJC_CLASS_$_InjectionNext", referenced from:  
       in ClientBoot.o  
  "_hookKeyPaths", referenced from:  
      +[NSObject(InjectionBoot) load] in InjectionBoot.o  
  "_injection_getKeyPath", referenced from:  
      +[NSObject(InjectionBoot) load] in InjectionBoot.o  
  "_swift_getKeyPath", referenced from:  
      +[NSObject(InjectionBoot) load] in InjectionBoot.o  
ld: symbol(s) not found for architecture arm64  
clang++: error: linker command failed with exit code 1 (use -v to see invocation)  

```

Important observation:
I've noticed that in the SourcePackages directory, the imported DLKit contains a method with the @_cdecl("DLKit_appImagesContain") attribute. However, for some reason, this symbol is not being found during the linking process.

Steps to reproduce:
1. Create a new Xcode project
2. Integrate InjectionNext as a Swift Package
3. Build the project

Expected behavior:
The project should build successfully, with all symbols properly linked.

Actual behavior:
The build fails with the above linker errors.

Environment:
- Xcode version: Version 16.0 beta 4 (16A5211f)
- macOS version: [15.0 Beta (24A5309e)]

Could you please advise on how to resolve these linker errors? Is there any additional configuration needed when integrating InjectionNext as a Swift Package?

Thank you for your help!

**Comment by wolfcolony** [comment]
![Uploading 3cfab5fdfa5c9e63072f7fcc9.png…]()

**Comment by johnno1962** [comment]
Hi, how did you "Integrate InjectionNext as a Swift Package" and is your project an Objective-C project?

**Comment by wolfcolony** [comment]
My original project was using Cocoapods and was a mix of Objective-C and Swift. After introducing InjectionNext, I encountered these errors. To isolate the issue, I created a new pure Swift project and integrated InjectionNext as a Swift Package, but I'm still facing the same "symbol not found" errors.

**Comment by wolfcolony** [comment]
![Xnip2024-08-07_20-10-31](https://github.com/user-attachments/assets/bda8fda3-fb83-48c1-a2f4-761bbb067cc1)

**Comment by wolfcolony** [comment]
Absolutely, I created a simple project with nothing added, and then added the 'InjectionNext' package through Files -> Add Package Dependencies. This is the initial setup for the Demo project. Here is my Demo: 
[TestInjection.zip](https://github.com/user-attachments/files/16530438/TestInjection.zip)

**Comment by wolfcolony** [comment]
Thank you very much for your help. I realized that I only needed to add one, and it indeed compiled successfully. I apologize for not noticing the difference between `InjectionNext` and `InjectionNextDynamic`, as I hadn't looked closely at the code, so I thought I needed to add both.

If I may, I'd like to ask a couple more questions:

What's the difference between `InjectionNext` and `InjectionNextDynamic`? Why are there two libraries?

I have a large project that mixes Objective-C and Swift, managed with CocoaPods and includes a Swift Module Map. Will `InjectionNext` work well in this context? I've just successfully run the demo, but I'm not sure what issues I might encounter in a large mixed-language project.

Thank you for your help and for your response.

**Comment by johnno1962** [comment]
There are two libraries, a statically linked one and a dynamic (framework) one in case a project shared some code with the InjectionNext implementation which could cause duplicate symbols on linking. In practice, you should use only `InjectionNext` unless you encounter this problem.

Integration with a large project is an open question a some would rather avoid adding Swift Packages. In this case there is the alternative of pre-built binary bundles which is being developed at the moment which some find easier. It also has its advantages in terms of support but is currently undocumented. It's going to be the same as for InjectionIII in that you add a build phase to copy the bundle into your app package and load the bundle using the snippet of code outlined in the [InjectionIII readme](https://github.com/johnno1962/InjectionIII?tab=readme-ov-file#injection-on-an-ios-tvos-or-visionos-device).

**Comment by wolfcolony** [comment]
Thank you very much for your detailed and patient explanation. I understand that InjectionNext offers both static library and dynamic framework options, as well as the alternative of pre-built binary bundles. I will try implementing InjectionNext in my project to see if I encounter any issues in practice. If I face any difficulties during the integration process, I hope I can consult you again. The information you've provided is extremely helpful, and I once again thank you for your patient guidance and professional clarification.
