### ISSUE TITLE
Build Error: Unknown argument: '-framework XCTest -lXCTestSwiftSupport'

### ISSUE THREAD

**Issue by yudonlee** [johnno1962/InjectionNext#16]
Hello,I encountered the following compilation error while setting up the real device.
`Unknown argument: '-framework XCTest -lXCTestSwiftSupport'`

The reproduction steps are as follows:
	1.	Create a new project.
	
	 
	2. Add XCTest framework on Build Phase
	
<img width="1223" alt="image" src="https://github.com/user-attachments/assets/eaa38354-ddde-4f07-b2f6-6c8c51a41bf4">

	3. Add -framework XCTest -lXCTestSwiftSupport to the Other Linker Flags setting.
<img width="870" alt="image" src="https://github.com/user-attachments/assets/59184410-8ecd-4cad-9123-4ebd9fbf821a">

	4. Compile the project and encounter the error. 
	`Framework 'XCTest -IXCTestSwiftSupport' not found`
	
	

Is there anything I did wrong?

**Comment by johnno1962** [comment]
Hi, XCTest -IXCTestSwiftSupport need to be on separate lines though why are you adding them there??
