### ISSUE TITLE
Build fails when adding InjectionNextDynamic

### ISSUE THREAD

**Issue by regenrek** [johnno1962/InjectionNext#20]
Hey,

* if I add InjectionNextDyanmic (typo) the build fails. I'm confused about the dynamic package. 

Is it mandatory?

![image](https://github.com/user-attachments/assets/80039e1a-5238-4558-81fa-55f415bb290c)

Error:

![image](https://github.com/user-attachments/assets/310d55a7-2da0-45ff-9ab1-377f9a86ccd0)

Regards

**Comment by johnno1962** [comment]
Hi, you need to add one or the other (See the Package.swift for more details). The "Dynamic" version is there only for when people's apps link with fishhook or other code in the client already. Unfortunately, newer versions of Xcode make it easy to add both by default.
