### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by genkernel** [johnno1962/InjectionNext#25]
Hi.

Im coming from [HotReloading](https://github.com/johnno1962/HotReloading).
When using HotReloading as an added spm package I encountered `duplicated symbols` errors every time I changed & tried to build another target (within the same xcode project).
I did not have `duplicated symbols` error without HotReloading so I attributed it to HotReloading (maybe wrongly).

Not sure if things will be better with InjeectionNext but I like what I see in the description so Im giving it a try.

I cant get InjectionNext to work though.
Here is what I did to my project:
I removed HotReloading package. 
I added InjectionNext package and linked it.
I left HotSwiftUI linked.
In addition I downloaded InjectionNext using the latest binary on gh.

I used InjectionNext to restart Xcode via `Launch Xcode`.

Here is what I see in logs when running:
`InjectionNext/Could not connect: Connection refused`
In addition I noticed menu item `Show Last error` in InjectionNext itself, it shows:
`
ld: warning: search path '/Applications/InjectionNext.app/Contents/Frameworks' not found
ld: warning: search path '/Applications/InjectionNext.app/Contents/Frameworks' not found
ld: building for 'macOS', but linking in object file (/private/tmp/injectionNext_0.o) built for 'iOS-simulator'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

InjectionNext icon is yellow.
This is on M1 and Im building for iOS Simulator.

Thanks for checking!

**Comment by genkernel** [comment]
One more ask, is it possible to launch InjectionNext -> Xcode from a terminal? Something like Im launching InjectionNext giving it xcode's prj file (or workspace) and it automatically launches xcode saving those menu taps.

**Comment by johnno1962** [comment]
Are you trying to use InjectionNext on a real device ? If so you need to use the menu item "Enable Devices" to allow the connection from your device to connect. While you see the error "Could not connect" and the icon is not orange it will not work.

**Comment by genkernel** [comment]
> Are you trying to use InjectionNext on a real device ? If so you need to use the menu item "Enable Devices" to allow the connection from your device to connect the network. While you see the error "Could not connect" and the icon is not orange it will not work. There is no way to launch with a specific workspace from the command line.

Nope. I cant get it to work on Simulator and above logs are from running on Simulator.

Just to add more context I see different logs when running on device:
`
🔥 InjectionNext: Locating developer's Mac. Have you selected "Enable Devices"?
Broadcasting to ... to locate InjectionNext host...
`

Im not looking to make it work on device.

**Comment by johnno1962** [comment]
It's as if you're running InjectionIII instead of the InjectionNext.app which uses a different port. It's very strange tha it would be unable to connect over localhost.

**Comment by genkernel** [comment]
It looks like it opens 8887 port OK:
`
(base) ~ ➤ netstat -an | grep 888                                                                                      
tcp4       0      0  127.0.0.1.8887         *.*                    LISTEN     
tcp6       0      0  ::1.8888               *.*                    LISTEN     
tcp4       0      0  127.0.0.1.8888         *.*                    LISTEN 
`

I dont remember it triggering apple's Firewall warning whether I'd like to allow the app to receive incoming connections. (system not asking for localhost interface?)

**Comment by johnno1962** [comment]
It seems contradictory that it would not connect, very very strange. You don't get a firewall prompt for localhost. As you are coming from HotReloading have you performed a build clean since switching to the InjectionNext package. Are you running the InjectionIII app still? If you get really stuck I could zoom if you send an invitation to GitHub at johnholdsworth.com.

**Comment by genkernel** [comment]
A quick update on this:

I tried using copy with Build Phase step instead of adding as a swift package.
This wasn't working. However it showed a bunch of errors related to rsync not being able to copy files. I solved it with  `user script sandboxing = NO`. This is not mentioned in README so I thought I'd mention it.

I tried again this time on device and it was not working either.
As I switched back to run on Sim I forgot to switch OFF `Enable Devices` mode. Unexpectedly it began to work in Sim with `Enabled Devices` mode ON.

RN if I run on Sim with `DEvices` mode ON reloading works OK. If I run on Sim with `Devices` OFF then it does not work.
And I see respective logs, either:
```
🔥 InjectionNext: iPhoneSimulator connection to app established, waiting for commands.
🔥 Platform connected: iPhoneSimulator
```
or 
```
InjectionNext/Could not connect: Connection refused
```

**Comment by genkernel** [comment]
Yeah, so after having it working via `Build Phase` method I decided to revert back to swift package - since it looked like it is a matter of having `Enable Devices` option turned on.

As I did that it stopped working with dlopen error and telling me to use `Unhide symbols`.
Unhide symbols worked before with Build phase. However it did not work this time.

Im not sure maybe I was supposed to clean rebuild or wipe Simulator or else.
At this point I switched to what was working.

**Comment by genkernel** [comment]
Yeah, thanks! I found that my project failed to build when I switched between targets with `duplicated symbols` error when using InjectionIII and I was forced to clean-rebuild every time I switched an active target.
Also reloading would not always work: for some deep in the app views it would fail to reload, while the very first presented view would reload just OK.

I didn't do much building with InjectionNext yet but it looks like `Enable Devices` and `Unhide Symbols` are my friends.

**Comment by genkernel** [comment]
> One more ask, is it possible to launch InjectionNext -> Xcode from a terminal? Something like Im launching InjectionNext giving it xcode's prj file (or workspace) and it in turn automatically launches xcode saving those menu taps.

Is this smth you may consider doing or do you think I may be able to tackle / add such a feature myself?

**Comment by johnno1962** [comment]
You may far better avoiding duplicate symbols with the new version as the "unhiding" story is a bit better. Re: hot reloading not always working are you adding an @ObserveInjection var at all levels, not just the top one. Re: a being able to launch InjectionNext with Xcode open with a project open that may not be too difficult to do. You'd be welcome to have a look at it.

**Comment by johnno1962** [comment]
I've gone ahead and implemented -projectPath argument for the app which you can use from the command line and made a new 1.2.5RC3 release candidate if you want to try it out. See the REAME for details.

**Comment by genkernel** [comment]
> I've gone ahead and implemented -projectPath argument for the app which you can use from the command line and made a new 1.2.5RC3 release candidate if you want to try it out. See the REAME for details.

Thank you. Much appreciated! I've just tried using `-projectPath` arg and it works!

Also it launched InjectionNext with `Enable Device` option disabled and hot reloading was working.

**Comment by johnno1962** [comment]
Networks huh? ¯\_(ツ)_/¯
