### ISSUE TITLE
XCode 16 supported?

### ISSUE THREAD

**Issue by rssole** [johnno1962/InjectionNext#26]
My usual setup working like a charm in XCode 15.4 is giving the following when I have switched to XCode 16:

`/iOS 16.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libXCTestSwiftSupport.dylib' (no such file)
🔥 Injection failed to load. If this was due to a default argument. Select the app's menu item "Unhide Symbols".`

I haven't changed or tried anything different in InjectionNext app itself?

Any advice on what to try?

Edit: I do know that running on device requires that XCTestSwiftSupport but I am trying with simulator...

**Comment by johnno1962** [comment]
Can you try the release candidate? This error should be suppressed in that version.

**Comment by rssole** [comment]
Argh sorry, I should have checked if there is some new version, yeah RC works as expected. Sorry for disturbance in the force.

**Comment by rssole** [comment]
As advised by @johnno1962 RC does not have this issue.
