### ISSUE TITLE
InjectionNext doesn't allow app to build on device

### ISSUE THREAD

**Issue by Perjan** [johnno1962/InjectionNext#27]
I integrated InjectionNext yesterday after transitioning from InjectionIII.
So far I loved it when building on the simulator. 

Unfortunately it doesn't allow the project to build on a real device.

### App Structure
- App
  - InjectionNext
  - Inject
  - CustomFramework1
    - Inject
    - InjectionNext

### What I tried
- InjectionNext app on/off
- Enable Devices on/off
- Open Xcode manually

This is the build error.

![CleanShot 2024-10-31 at 12 00 50@2x](https://github.com/user-attachments/assets/a0a9ea60-e9c0-4b28-81b5-32d9ae65b784)

Please @johnno1962 help me solve it, because this is blocking me from submitting to the App Store.
Thanks.

**Comment by Perjan** [comment]
Here is the error log as well.
[Error-InjectionNext.txt](https://github.com/user-attachments/files/17586854/Error-InjectionNext.txt)

**Comment by johnno1962** [comment]
This is Xcode 16.1 right? Can you try turning off the "Undefined behaviour Sanitizer" in your scheme?

<img width="651" alt="image" src="https://github.com/user-attachments/assets/c930ec75-e137-46ae-ae69-c19cbf8e706d">

**Comment by Perjan** [comment]
I turned it off. Now it works. Thanks John.
The app runs fine on the device.

**Comment by johnno1962** [comment]
It's a strange problem. I have a project which by chance replicates what you've seem in Xcode 15 as well when you build for device with "Undefined behaviour Sanitizer" but, when I tried to prepare a replicating project for Apple I couldn't get it to fail and can't see what the difference would be. ¯\\\_(ツ)\_/¯. Any other strange problems with InjectionNext let me know!

**Comment by Perjan** [comment]
I am working on Xcode 16.1. Maybe having frameworks that also have InjectionNext and Inject as dependencies might trigger it?

**Comment by johnno1962** [comment]
I tried adding a framework but it doesn't seem to be that. Seems to be a very odd edge case in the build system related to the InjectionLite or DLKit framework which I have a smallish replicating project which doesn't build for simulator or device, so I raised FB15653175.
