### ISSUE TITLE
Works great on Xcode; Not on Cursor

### ISSUE THREAD

**Issue by titoAtChannel** [johnno1962/InjectionNext#28]
Hello,

I'm able to use `InjectNext` perfectly fine in Xcode 15.4. However, I cannot do that in the `Cursor` IDE. InjectNext requires that I select Xcode, but there doesn't seem to be a way to do the same with `Cursor`. Or is there a step I'm missing?

This is the output I get:

```
 *  Executing task: sweetpad: launch 

🚀 Executing command:
xcodebuild ARCHS\=arm64 VALID_ARCHS\=arm64 ONLY_ACTIVE_ARCH\=NO -scheme CursorDemo -configuration Debug -workspace /Users/tito/CursorDemo/CursorDemo.xcodeproj/project.xcworkspace -destination 'platform=iOS Simulator,id=86E85796-3B03-41E3-BC91-C98E8055C6D8' -resultBundlePath '/Users/tito/Library/Application Support/Cursor/User/workspaceStorage/aa421656b6e531be70a1302f49a95e20/sweetpad.sweetpad/bundle/CursorDemo' -allowProvisioningUpdates build


----- xcbeautify -----
Version: 2.14.1
----------------------

Resolving Package Graph
Resolved source packages
InjectionNext - https://github.com/johnno1962/InjectionNext @ 1.2.5
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:86E85796-3B03-41E3-BC91-C98E8055C6D8, OS:17.5, name:iPhone 15 Pro }
{ platform:iOS Simulator, id:86E85796-3B03-41E3-BC91-C98E8055C6D8, OS:17.5, name:iPhone 15 Pro }
[CursorDemo] Compiling ContentView.swift
[CursorDemo] Copy arm64-apple-ios-simulator.abi.json -> CursorDemo.abi.json
[CursorDemo] Copy arm64-apple-ios-simulator.swiftsourceinfo -> CursorDemo.swiftsourceinfo
Signing CursorDemo.app (in target 'CursorDemo' from project 'CursorDemo')
Build Succeeded

🚀 Executing command:
open -a Simulator

🚀 Executing command:
xcrun simctl install 86E85796-3B03-41E3-BC91-C98E8055C6D8 /Users/tito/Library/Developer/Xcode/DerivedData/CursorDemo-dcojtnqoqfkxnhclzdvgiqfererd/Build/Products/Debug-iphonesimulator/CursorDemo.app

🍭 Sweetpad: watch marker (start)
🍩 Sweetpad: watch marker (end)

🚀 Executing command:
xcrun simctl launch --console-pty --terminate-running-process 86E85796-3B03-41E3-BC91-C98E8055C6D8 com.webbo.CursorDemo

2024-11-08 12:32:34.191 CursorDemo[41047:532654] InjectionNext/Could not connect: Connection refused
```

The reason I'm using `InjectionNext` is due to `InjectIII` failing to locate cached data.

Is there a way to get Cursor to work with `InjectionNext`?

Thanks!

**Comment by johnno1962** [comment]
Hi, InjectionNext, you could say, is dependent on Xcode, so you need to work out what the problem was with InjectionIII. Are you using a custom derived data path by any chance?

**Comment by titoAtChannel** [comment]
Not really. It's as standard as it could be. I could post the output? Perhaps that could give you a hint.

**Comment by titoAtChannel** [comment]
@johnno1962 should I paste the output here, or would it be better to open a ticket in the `InjectionIII` project page?

**Comment by titoAtChannel** [comment]
The gist of the issue seems to be:
```
💉 ⚠️ Re-compilation failed (see: /Users/tito/Library/Containers/com.johnholdsworth.InjectionIII/Data/tmp/command.sh)
<unknown>:0: error: fatal error encountered during compilation; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
<unknown>:0: note: cannot get default cache directory
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
```

**Comment by johnno1962** [comment]
That's a new error. Which version of Xcode/macOS is this? Actually, more to the point you seem to be using the App Store version of InjectionIII, can you download one of the more recent binary releases and try it out. https://github.com/johnno1962/InjectionIII/releases

**Comment by titoAtChannel** [comment]
Sure thing. More info:

Mac OS X Sonoma 14.7 (23H124)
Xcode Version 15.4 (15F31d)

**Comment by titoAtChannel** [comment]
Ah! Version 5.0.5 worked!:
```
💉 InjectionIII connected /Users/tito/CursorDemo/CursorDemo.xcodeproj
💉 Watching files under the directory /Users/tito/CursorDemo
💉 Compiling /Users/tito/CursorDemo/CursorDemo/ContentView.swift
💉 Loading .dylib ...
💉 Interposed 6 function references.
💉 Injected type #1 'CursorDemo.ContentView'
```

**Comment by titoAtChannel** [comment]
I'm not the type of typically jumping to the new, coolest gadgets, but Xcode has been falling behind a lot. Buggy and crashes quite a bit. Weird that the Xcode team doesn't care about long-standing bugs. Oh well! Cursor works very, very well. If you can make it work with InjectionNext, a lot of us will be very, VERY happy. Thank you John!

**Comment by johnno1962** [comment]
The message you're seeing is likely because the app is trying to run the compiler inside a sandbox so it's not Apple's fault.

**Comment by titoAtChannel** [comment]
Oh, I'm not saying is Apple's fault. Perhaps it's a matter of giving `InjectionIII` full disk access? All these security settings are maddening.

**Comment by johnno1962** [comment]
OK, so I've pushed a new version of InjectionNext which you can run without the Xcode integration if you want to try it out: https://github.com/johnno1962/InjectionNext/releases/tag/1.2.6RC1.

You run InjectionNext instead of InjectionIII but instead of launching Xcode using the app you use the "Watch Project" menu item which falls back to a legacy file watcher and log parser that can be used with Cursor (cc: @rudrankriyam)

**Comment by rudrankriyam** [comment]
Yay!! I am literally writing about InjectionNext so thank you @titoAtChannel for raising the issue and thank you so much @johnno1962 for making it compatible for us! 🚀

**Comment by titoAtChannel** [comment]
Amazing! Works like a charm! Thank you @johnno1962  so much! 🙏🏻 @rudrankriyam please let us know when you publish the article. Would love to read it.
