### ISSUE TITLE
Injection menu item freezes when selecting "Open Xcode project"

### ISSUE THREAD

**Issue by bradwrage** [johnno1962/InjectionNext#30]
Upon selecting "Open Xcode project" the menu freezes and stays open. I am also unable to take any other action on my computer until I go to quite the task in activity monitor. 
<img width="242" alt="menu" src="https://github.com/user-attachments/assets/795fa1bb-1e5d-4181-bc63-ff60ad6c1fe0">

**Comment by johnno1962** [comment]
I've updated the release candidate moving injections onto the main thread which might resolve this. I've not been able to replicate it.
