### ISSUE TITLE
fail run simulator in xcode 16.1

### ISSUE THREAD

**Issue by iOSleep** [johnno1962/InjectionNext#32]
on device success
simulator fail 
xcode16.1
InjectionNext 1.2.5

for simulator just add InjectionNext by swift package, and set OTHER_LDFLAGS

![image](https://github.com/user-attachments/assets/56a3ad6c-167b-47f8-982c-422f262f5f06)

**Comment by johnno1962** [comment]
Hi, you seem to be loading the iOSInjection.bundle from InjectionIII. Are you loading it in your app's main? If not try renaming your /Applications/InjectionIII.app.

**Comment by iOSleep** [comment]
thanks, old macro code load the bundle frome InjectionIII, and i success when i try again
