### ISSUE TITLE
1.2.6 RC5 cannot connect with either Xcode or Cursor

### ISSUE THREAD

**Issue by diederikh** [johnno1962/InjectionNext#33]
When I try 1.2.6 RC5 with Xcode or Cursor I get an error in the logs when SwiftUI tries to inject:

```
InjectionClient/Could not connect: Connection refused
💉 Not falling back to standalone HotReloading as you are using the ‘Inject’ package. Use MenuBar app to control Injection status or opt in by using INJECTION_STANDALONE env var.
```

Running InjectIII for the same project works fine. 
Is a different port used for Next?

**Comment by diederikh** [comment]
I've tried with the InjectNext package. 
The app connects now:
```
🔥 InjectionNext: iPhoneSimulator connection to app established, waiting for commands.
🔥 Platform connected: iPhoneSimulator
```

However updating an SwiftUI view yields this error:
```
🔥 Recompiling: /Users/diederik/Development/Medable/ios-app/App/PatientApp/Patient Journey/Views/ScheduleView.swift
🔥 ⚠️ Recompile failed for: /Users/diederik/Development/Medable/ios-app/App/PatientApp/Patient Journey/Views/ScheduleView.swift
<unknown>:0: error: unknown argument: '-driver-show-incremental'
<unknown>:0: error: unknown argument: '-driver-show-job-lifecycle'

🔥 ⚠️ Injection failed. Was your app connected?
```

**Comment by johnno1962** [comment]
It uses the swiftc in the version of Xcode you select. Which version of Xcode are you using? The first error I can probably resolve quite easily by tripping out those options. The second error, another user has reported and I'd like to get to the bottom of. In the line previous to the "Current log:" value it should have listed the complete command line being executed. Are you able to email that to GitHub at johnholdsworth dot com or post it here?

**Comment by diederikh** [comment]
I'm using Xcode 16.0

**Comment by johnno1962** [comment]
Thanks for the log, I've created a new release candidate removing these spurious options if you'd like to give it a try https://github.com/johnno1962/InjectionNext/releases/tag/1.2.6RC6.

**Comment by diederikh** [comment]
That build fixed the Xcode issue. Cursor still fails with a different error. I'll email you the logs for the Cursor one.

**Comment by johnno1962** [comment]
I wonder, can you try turning off the following build setting:

<img width="668" alt="image" src="https://github.com/user-attachments/assets/56d7897f-b0a6-4e17-8e18-08adabb39d5a">

**Comment by johnno1962** [comment]
I've uploaded a fix of sorts for the .pch problem: https://github.com/johnno1962/InjectionNext/releases/tag/1.2.6RC7

**Comment by johnno1962** [comment]
Great! Thanks for getting back. With luck, RC8 should work even without that option turned off.
