### ISSUE TITLE
error: no such module 'UnityFramework'

### ISSUE THREAD

**Issue by gonchar** [johnno1962/InjectionNext#34]
Hello,

Decided to give it a try and switch to InjectionNext. I get this error. Do you know how can I fix that? it worked before with InjectionIII.app

```
/Users/user/Documents/App/Views/rendering/UnityRenderingEngine.swift:8:8: error: no such module 'UnityFramework'
  6 | //
  7 | 
  8 | import UnityFramework
    |        `- error: no such module 'UnityFramework'
  9 | import Combine
 10 | 
```

at the same time, InjectionNext works great if my iOS target doesn't include UnityFramework.framework

UnityFramework is just separately compiled framework which is connected like that to my iOS target
<img width="578" alt="Screenshot 2024-12-21 at 19 41 17" src="https://github.com/user-attachments/assets/0c2022b4-2839-4664-9e21-4d09f4d94aec" />

**Comment by johnno1962** [comment]
HI, thanks for the info. Frameworks need to be available at compile time as well so the easiest thing to do is symbolically link it into the "PackageFrameworks" directory of your DerivedData,the path to which you should see in your build logs.

**Comment by gonchar** [comment]
Thank you so much! Everything works now
