### ISSUE TITLE
@Observable, #Preview, or macros in general: not supported?

### ISSUE THREAD

**Issue by andrebraga** [johnno1962/InjectionNext#4]
`error: external macro implementation type 'ObservationMacros.ObservableMacro' could not be found for macro 'Observable()'; plugin for module 'ObservationMacros' not found`
`error: external macro implementation type 'PreviewsMacros.SwiftUIView' could not be found for macro 'Preview(_:body:)'; plugin for module 'PreviewsMacros' not found`

Xcode 16 beta 3, vanilla SwiftUI app using a trivial `@Observable` view model, and a very plain

```
#Preview {
    ContentView()
}
```

Did I miss some step in the configuration?

**Comment by johnno1962** [comment]
Hi, It mentions in the README you need to surround your #Preview macro with #if !INJECTING. I wasn't aware of the problem with @Observable though. I'll have to find a solution for this, other macros seem to work. It's just the builtin ones which are missing a path parameter somewhere.

**Comment by innoscale-andre** [comment]
> Hi, It mentions in the README you need to surround your #Preview macro with #if !INJECTING.

I'm officially blind 😝 

> I wasn't aware of the problem with @observable though. I'll have to find a solution for this, other macros seem to work. It's just the builtin ones which are missing a path parameter somewhere.

Might be an Xcode-16-related regression 🤔

**Comment by andrebraga** [comment]
> Hi, It mentions in the README you need to surround your #Preview macro with #if !INJECTING.

I'm officially blind 😝 

> I wasn't aware of the problem with @observable though. I'll have to find a solution for this, other macros seem to work. It's just the builtin ones which are missing a path parameter somewhere.

Might be an Xcode-16-related regression 🤔

**Comment by johnno1962** [comment]
I've uploaded a new version of the app which should support injecting files containing compiler's builtin macros & #Previews. Let me know how you get on.

**Comment by andrebraga** [comment]
It's up and running and hooking! But I'm getting a semi-immediate crash on `AttributeGraph'AGGraphSetOutputValue:` when changing something in the body of a SwiftUI view (1 letter in the placeholder text of a TextField).

**Comment by johnno1962** [comment]
Thanks for getting back so quickly. Can you paste the section of SwiftUI code which is crashing here?

**Comment by andrebraga** [comment]
[Test.zip](https://github.com/user-attachments/files/16197411/Test.zip)
Whole test project. It crashes if you change this string here, save, then focus on one of the text fields.

So:
<img width="940" alt="image" src="https://github.com/user-attachments/assets/de051c78-b3ca-4c57-8a93-ab31cf1eac1c">
to
<img width="941" alt="image" src="https://github.com/user-attachments/assets/ab002a4e-389b-4525-84ed-094fe91c4d7d">
then touch the first field, Xcode goes
<img width="941" alt="image" src="https://github.com/user-attachments/assets/32894419-2947-412c-ba88-69a02984a470">

**Comment by johnno1962** [comment]
Thanks for the Test project, that's always a big help. I noticed any after any injection, even without a change anything would cause a crash when you tried to do anything then I noticed you hadn't added the secret sauce for injecting SwiftUI at the end of your View body. After adding the following it seems to start working.
```
        .enableInjection()
    }
    
    @ObserveInjection var redraw
```
These functions erase the return type protecting it from changes in memory layout and force the view to redraw and are available in the https://github.com/johnno1962/HotSwiftUI or https://github.com/krzysztofzablocki/Inject projects.

**Comment by andrebraga** [comment]
Jackpot!

This is just too good! :)

Thank you, John!

**Comment by andrebraga** [comment]
Quick question though: isn't this supposed to be handled by the code in Experimental? I haven't looked deeply into that, just noticed that the functionality is (?) there. Not enabled for now?

**Comment by johnno1962** [comment]
Thanks for reminding me, I've made an update to the regular expression implementing this to cope with un-indented #conditionals and pushed out a new 1.1.0 app release. Anything else, let me know.
