### ISSUE TITLE
ObserveInjection too restricted?

### ISSUE THREAD

**Issue by andrebraga** [johnno1962/InjectionNext#5]
https://github.com/johnno1962/InjectionNext/blob/e8b0a356620d9dab34aa20dc58cc6f150bee5a81/App/InjectionNext/Experimental.swift#L105

Any reason to lock this to iOS? If the sole dependency there is on `ObservableObject`, why not replicate its availability?
`@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)`

It could also be a `#if canImport(SwiftUI) && canImport(Combine)` at the top and not check availability at all for `ObserveInjection`, since (it seems!) the injection machinery only uses core SwiftUI types available since day 1...

**Comment by johnno1962** [comment]
Thanks for pointing this out, I've pushed a new commit opening things up. This code in Experimental.swift is kind of a fallback and people have found it useful to understand what is going on behind the scenes. You'd normally import the HotSwiftUI or Inject projects.

**Comment by andrebraga** [comment]
Sometimes it's easier to convince stakeholders (managers or teammates alike) if the number of dependencies is kept minimum... Technically speaking, what's the upside of adopting Inject or HotSwiftUI in place of the "fallback"?

**Comment by johnno1962** [comment]
There is no upside to HotSwiftUI as it is the same code except you can use it in multiple targets. The same applies to Inject but it takes the idea a bit further and explores "hosting" where you can wrap the instantiation of your UIViewController subclass in a way it gets re-instantiated on injection.
